default: &default
  adapter: postgresql
  template: template0
  encoding: unicode
  username: ildarsafin
  host: localhost
  password:
  pool: 5

development:
  <<: *default
  database: reflections_development

test:
  <<: *default
  database: reflections_test

production:
  <<: *default
  url: <%= ENV.fetch("POSTGRESQL_URL", "") %>
