default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: reflections_development

test:
  <<: *default
  database: reflections_test

production:
  <<: *default
  url: <%= ENV.fetch("POSTGRESQL_URL", "") %>
